### PR TITLE
Upgrade to dotnet standard 2.1 and minor fixes

### PR DESCRIPTION
**Pull request by alercunha**
Hi @devjoes, great little library you have here. I've been using your library for the past few months and it has served me greatly during my implementation of end-to-end tests that require a container of some sort (MSSQL, Datastore Emulator, etc).

I had to make a few changes to your lib in order to fit my projects which are all based on dotnet core 3.1 and standard lib 2.1.
So I'm contributing back my changes and hopefully you can merge and publish a new version of your library so I can pull directly from Nuget.

Let me know if you have any questions or need any help.

Thanks!
Ale Cunha.

### CODE REVIEW

**Comment by JoeSainsburys** [comment]
Thanks for the PR, will review in a day or two. If your just using it to spin up databases etc then you might be interested in https://github.com/devjoes/DockerizedTesting

**Comment by alercunha** [comment]
> Thanks for the PR, will review in a day or two. If your just using it to spin up databases etc then you might be interested in https://github.com/devjoes/DockerizedTesting

That looks fantastic. I guess I have one more "upgrade to dotnet standard 2.1" to do now... :)

**Review by JoeSainsburys — APPROVED** [review]

**Comment by JoeSainsburys** [comment]
New package here: https://www.nuget.org/packages/DockerComposeFixture/1.1.0
Thanks for the PR

**Comment by alercunha** [comment]
Perfect, thanks a lot!

If I have time I'll do the same for the other repo you have.

Cheers,
Alex.

**Pull request merged**
